# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfe9d7390f403ff2285fa18c97457b7d951eb47b4340980501ce262f615b53334fd4a6e63fbddb058816f7df5cf280efc17c82f0b5614363f938dcba728c5c7e

test:
  secret_key_base: e40652506e5fd027e7e83af07ff22862d48e2cc54c29d42e8fdd018099094c692794ab5b6366c85781da98e28c31ffeb8e1b21823d4c8b72ddadb4ac2ed386a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
